(* Links from the documentation to https://www.symmetricfunctions.com/ (SymCat).
   "packages": background pages per package. "symbols": {package, name pattern, page}; the
   first matching rule gives a symbol its "Background" link. Pages are file names on the site;
   Scripts/BuildDocs.m checks them against Scripts/docs/symcat-pages.tsv (page names and titles, taken from the built site). *)
<|
"packages" -> <|
  "SymmetricFunctions" -> {"standardSymmetricFunctions", "schur", "littlewoodRichardson", "plethysm", "jack", "hallLittlewood", "macdonaldP", "macdonaldH", "llt"},
  "ShiftedSymmetricFunctions" -> {"schurShifted", "jackShifted"},
  "CombinatoricTools" -> {"preliminaries", "q-analogs", "kostkaFoulkes"},
  "NewTableaux" -> {"preliminaries", "rsk", "crystals", "tableauOperators", "borderStripTableaux"},
  "GTPatterns" -> {"gtpatterns", "hivePolytopes", "ehrhart"},
  "QuasiSymmetricFunctions" -> {"standardQuasiSymmetricFunctions", "gessel", "qsymSchur"},
  "NonsymmetricPolynomials" -> {"key", "schubert", "grothendieck", "lascoux", "assaf", "macdonaldE", "macdonaldEperm"},
  "PolynomialTools" -> {"realRooted", "realRootedInterlacing", "eulerian", "gammaPositivity", "ehrhart"},
  "PermutationTools" -> {"permutations", "permutationPatterns", "permutationFamilies"},
  "CatalanObjects" -> {"combinatorialObjects", "parking-functions", "qtCatalan"},
  "UnicellularChromatics" -> {"chromaticQuasisymmetric", "chromaticEexpansion", "unicellular-llt"},
  "MatroidTools" -> {"matroids", "lattice-path-matroids"},
  "PosetData" -> {"posets", "pPartitions"}
|>,
"symbols" -> {
  {"SymmetricFunctions", "SkewSchur*" | "Schur*", "schur"},
  {"SymmetricFunctions", "LR*", "littlewoodRichardson"},
  {"SymmetricFunctions", "Plethysm*", "plethysm"},
  {"SymmetricFunctions", "Jack*", "jack"},
  {"SymmetricFunctions", "HallLittlewood*", "hallLittlewood"},
  {"SymmetricFunctions", "MacdonaldH*", "macdonaldH"},
  {"SymmetricFunctions", "Macdonald*", "macdonaldP"},
  {"SymmetricFunctions", "LLT*" | "*LLT*", "llt"},
  {"SymmetricFunctions", "KSchur*" | "*KSchur*", "kschur"},
  {"SymmetricFunctions", "Lah*", "lah"},
  {"SymmetricFunctions", "Petrie*", "petrie"},
  {"SymmetricFunctions", "Kostka*" | "*Kostka*", "kostkaFoulkes"},
  {"SymmetricFunctions", "Monomial*" | "Elementary*" | "CompleteH*" | "PowerSum*" | "Forgotten*", "standardSymmetricFunctions"},
  {"ShiftedSymmetricFunctions", "ShiftedSchur*", "schurShifted"},
  {"ShiftedSymmetricFunctions", "ShiftedJack*", "jackShifted"},
  {"CombinatoricTools", "Kostka*" | "*Charge*" | "*Cocharge*", "kostkaFoulkes"},
  {"NewTableaux", "*RSK*", "rsk"},
  {"NewTableaux", "Crystal*" | "SSAFCrystal*", "crystals"},
  {"NewTableaux", "*Promotion*" | "*Evacuation*", "tableauOperators"},
  {"NewTableaux", "BorderStrip*", "borderStripTableaux"},
  {"NewTableaux", "AtomFillings" | "KeyFillings" | "TAtomFillings" | "SSYTToAtom", "key"},
  {"GTPatterns", "BZ*", "hivePolytopes"},
  {"GTPatterns", "GTEhrhart*" | "UpperBoundKostkaDegree", "ehrhart"},
  {"GTPatterns", "*", "gtpatterns"},
  {"QuasiSymmetricFunctions", "Fundamental*", "gessel"},
  {"QuasiSymmetricFunctions", "QuasiSchur*", "qsymSchur"},
  {"QuasiSymmetricFunctions", "*", "standardQuasiSymmetricFunctions"},
  {"NonsymmetricPolynomials", "Key*" | "Atom*" | "TKey*" | "TAtom*" | "Demazure*" | "TDemazure*" | "ToKeyBasis" | "ToAtomBasis", "key"},
  {"NonsymmetricPolynomials", "Schubert*" | "ToSchubertBasis" | "DividedDifference" | "PermutationToCode" | "CodeToPermutation", "schubert"},
  {"NonsymmetricPolynomials", "Grothendieck*" | "DualGrothendieck*" | "KDividedDifference" | "ToGrothendieckBasis", "grothendieck"},
  {"NonsymmetricPolynomials", "Lascoux*" | "KDemazureOperator" | "ToLascouxBasis", "lascoux"},
  {"NonsymmetricPolynomials", "FundamentalSlide*" | "Lock*" | "ToFundamentalSlideBasis" | "ToLockBasis", "assaf"},
  {"NonsymmetricPolynomials", "MacdonaldE*" | "IntegralMacdonaldE", "macdonaldE"},
  {"PolynomialTools", "*RealRoot*" | "*Interlac*", "realRooted"},
  {"PolynomialTools", "Eulerian*", "eulerian"},
  {"PolynomialTools", "Gamma*", "gammaPositivity"},
  {"PolynomialTools", "HStar*" | "HVector*" | "*Ehrhart*", "ehrhart"},
  {"PermutationTools", "*Avoid*" | "*Pattern*", "permutationPatterns"},
  {"UnicellularChromatics", "*LLT*", "unicellular-llt"},
  {"UnicellularChromatics", "*Chromatic*", "chromaticQuasisymmetric"},
  {"MatroidTools", "LatticePath*", "lattice-path-matroids"},
  {"MatroidTools", "*", "matroids"},
  {"PosetData", "*", "posets"}
}
|>
