(* The GitHub Pages site in docs/ is generated by Scripts/BuildDocs.m from the usage messages
   and the guides; regenerate it into a temporary directory and compare, so that it never
   drifts from the code. Fix a failure with: wolframscript -file Scripts/BuildDocs.m *)

docsFiles[dir_] := Sort[StringDrop[#, StringLength[dir] + 1] & /@
	Select[FileNames["*", dir, Infinity], !DirectoryQ[#] &]];

VerificationTest[
	Module[{tmp = CreateDirectory[], wolframscript, log, docs, fresh},
		wolframscript = FileNameJoin[{$InstallationDirectory, "Executables", "wolframscript"}];
		log = ReadList["!" <> StringRiffle[("'" <> # <> "'") & /@
			{wolframscript, "-file", FileNameJoin[{testRoot, "Scripts", "BuildDocs.m"}], tmp}], String];
		docs = FileNameJoin[{testRoot, "docs"}];
		fresh = {docsFiles[docs] === docsFiles[tmp],
			Select[docsFiles[tmp], ReadByteArray[FileNameJoin[{tmp, #}]] =!=
				Quiet[ReadByteArray[FileNameJoin[{docs, #}]]] &]};
		DeleteDirectory[tmp, DeleteContents -> True];
		fresh],
	{True, {}},
	TestID -> "Docs-site-is-up-to-date",
	TimeConstraint -> 120
]
