(* ::Package:: *)

(* Nonsymmetric polynomials: divided difference and Demazure operators, and the key,
   atom, t-key, t-atom and Schubert polynomial families generated by them (issue #51).
   Polynomials are expressions in x[1], ..., x[n]; families are also available as basis
   symbols (KeySymbol[alpha, x], ...) with conversions in both directions.
   Conventions (CONVENTIONS.md): keys and atoms are indexed by weak compositions in the
   standard way, kappa_(0,1) = x[1] + x[2], as in the Rust sym-poly library. *)

BeginPackage["NonsymmetricPolynomials`", {"AlgebraicBases`", "CombinatoricTools`"}];

VariableTransposition;
DividedDifference;
DemazureOperator;
DemazureAtomOperator;
TDemazureOperator;
TDemazureAtomOperator;
KDividedDifference;
KDemazureOperator;

KeyPolynomial;
AtomPolynomial;
TKeyPolynomial;
TAtomPolynomial;
SchubertPolynomial;
PermutationToCode;
CodeToPermutation;

KeySymbol;
AtomSymbol;
SchubertSymbol;
NonsymmetricToPolynomial;
ToKeyBasis;
ToAtomBasis;
ToSchubertBasis;
ClearNonsymmetricPolynomialsCache;

Begin["`Private`"];

(* Results of memoized public functions; the public symbols are protected. *)
npCache = <||>;
SetAttributes[cached, HoldRest];
cached[key_, expr_] := If[KeyExistsQ[npCache, key], npCache[key], npCache[key] = expr];

ClearNonsymmetricPolynomialsCache::usage = "ClearNonsymmetricPolynomialsCache[] removes all stored results of NonsymmetricPolynomials, such as computed key polynomials and basis transition matrices.";
ClearNonsymmetricPolynomialsCache[] := (npCache = <||>;);


(* ::Section:: *)
(* Operators *)

(* An operator applied to a list of indices {i1, ..., ik} means op_i1 op_i2 ... op_ik,
   so the last index acts first. *)
applyWord[op_, f_, word_List] := Fold[op[#1, #2] &, f, Reverse[word]];

VariableTransposition::usage = "VariableTransposition[f, x, i] interchanges x[i] and x[i+1] in f.";
VariableTransposition[f_, x_, i_Integer] := f /. {x[i] -> x[i + 1], x[i + 1] -> x[i]};

DividedDifference::usage = "DividedDifference[f, x, i] applies the divided difference operator (f - s_i f)/(x[i] - x[i+1]).\nDividedDifference[f, x, {i1, ..., ik}] applies the composition with i_k acting first.";
DividedDifference[f_, x_, i_Integer] :=
	Expand@Cancel[Together[(f - VariableTransposition[f, x, i])/(x[i] - x[i + 1])]];
DividedDifference[f_, x_, word_List] := applyWord[DividedDifference[#1, x, #2] &, f, word];

DemazureOperator::usage = "DemazureOperator[f, x, i] applies the isobaric divided difference (Demazure operator) pi_i f = DividedDifference[x[i] f, x, i].\nDemazureOperator[f, x, {i1, ..., ik}] applies the composition with i_k acting first.";
DemazureOperator[f_, x_, i_Integer] := DividedDifference[x[i] f, x, i];
DemazureOperator[f_, x_, word_List] := applyWord[DemazureOperator[#1, x, #2] &, f, word];

DemazureAtomOperator::usage = "DemazureAtomOperator[f, x, i] applies theta_i = pi_i - 1, the operator generating Demazure atoms.\nDemazureAtomOperator[f, x, {i1, ..., ik}] applies the composition with i_k acting first.";
DemazureAtomOperator[f_, x_, i_Integer] := Expand[DemazureOperator[f, x, i] - f];
DemazureAtomOperator[f_, x_, word_List] := applyWord[DemazureAtomOperator[#1, x, #2] &, f, word];

TDemazureOperator::usage = "TDemazureOperator[f, x, t, i] applies the t-deformed Demazure operator (1 - t) pi_i f + t s_i f.\nTDemazureOperator[f, x, t, {i1, ..., ik}] applies the composition with i_k acting first.";
TDemazureOperator[f_, x_, t_, i_Integer] :=
	Expand[(1 - t) DemazureOperator[f, x, i] + t VariableTransposition[f, x, i]];
TDemazureOperator[f_, x_, t_, word_List] := applyWord[TDemazureOperator[#1, x, t, #2] &, f, word];

TDemazureAtomOperator::usage = "TDemazureAtomOperator[f, x, t, i] applies the t-deformed atom operator (1 - t) theta_i f + t s_i f.\nTDemazureAtomOperator[f, x, t, {i1, ..., ik}] applies the composition with i_k acting first.";
TDemazureAtomOperator[f_, x_, t_, i_Integer] :=
	Expand[(1 - t) DemazureAtomOperator[f, x, i] + t VariableTransposition[f, x, i]];
TDemazureAtomOperator[f_, x_, t_, word_List] := applyWord[TDemazureAtomOperator[#1, x, t, #2] &, f, word];

KDividedDifference::usage = "KDividedDifference[f, x, beta, i] applies the connective K-theoretic divided difference DividedDifference[(1 + beta x[i+1]) f, x, i]; beta = 0 gives DividedDifference.\nKDividedDifference[f, x, beta, {i1, ..., ik}] applies the composition with i_k acting first.";
KDividedDifference[f_, x_, beta_, i_Integer] := DividedDifference[(1 + beta x[i + 1]) f, x, i];
KDividedDifference[f_, x_, beta_, word_List] := applyWord[KDividedDifference[#1, x, beta, #2] &, f, word];

KDemazureOperator::usage = "KDemazureOperator[f, x, beta, i] applies the K-theoretic Demazure operator KDividedDifference[x[i] f, x, beta, i], which defines Lascoux polynomials; beta = 0 gives DemazureOperator.\nKDemazureOperator[f, x, beta, {i1, ..., ik}] applies the composition with i_k acting first.";
KDemazureOperator[f_, x_, beta_, i_Integer] := KDividedDifference[x[i] f, x, beta, i];
KDemazureOperator[f_, x_, beta_, word_List] := applyWord[KDemazureOperator[#1, x, beta, #2] &, f, word];


(* ::Section:: *)
(* Families generated by operators *)

weakCompositionQ[alpha_] := VectorQ[alpha, IntegerQ[#] && # >= 0 &];

(* A word {i1, ..., ik} with s_i1 ... s_ik (sort(alpha)) = alpha, where s_i swaps
   positions i and i+1; the last letter acts first. Obtained by bubble-sorting alpha
   into weakly decreasing order. *)
sortingWord[alpha_List] := Module[{a = alpha, word = {}, swapped = True},
	While[swapped,
		swapped = False;
		Do[If[a[[i]] < a[[i + 1]],
			a[[{i, i + 1}]] = a[[{i + 1, i}]]; AppendTo[word, i]; swapped = True],
			{i, Length[a] - 1}]];
	word
];

monomial[alpha_List, x_] := Times @@ MapIndexed[x[First[#2]]^#1 &, alpha];

KeyPolynomial::usage = "KeyPolynomial[alpha, x] returns the key polynomial (Demazure character) kappa_alpha in x[1], x[2], ... for a weak composition alpha, computed as pi_w x^sort(alpha) with Demazure operators. Standard indexing: KeyPolynomial[{0, 1}, x] is x[1] + x[2].";
KeyPolynomial[alpha_?weakCompositionQ, x_] := cached[{KeyPolynomial, alpha},
	DemazureOperator[monomial[Sort[alpha, Greater], xx], xx, sortingWord[alpha]]] /. xx -> x;

AtomPolynomial::usage = "AtomPolynomial[alpha, x] returns the Demazure atom A_alpha in x[1], x[2], ... for a weak composition alpha, computed as theta_w x^sort(alpha). Standard indexing: AtomPolynomial[{0, 1}, x] is x[2].";
AtomPolynomial[alpha_?weakCompositionQ, x_] := cached[{AtomPolynomial, alpha},
	DemazureAtomOperator[monomial[Sort[alpha, Greater], xx], xx, sortingWord[alpha]]] /. xx -> x;

TKeyPolynomial::usage = "TKeyPolynomial[alpha, x, t] returns the t-deformed key polynomial obtained by applying TDemazureOperator along the sorting word of alpha to x^sort(alpha); t = 0 gives KeyPolynomial.";
TKeyPolynomial[alpha_?weakCompositionQ, x_, t_] := cached[{TKeyPolynomial, alpha},
	TDemazureOperator[monomial[Sort[alpha, Greater], xx], xx, tt, sortingWord[alpha]]] /. {xx -> x, tt -> t};

TAtomPolynomial::usage = "TAtomPolynomial[alpha, x, t] returns the t-deformed Demazure atom obtained by applying TDemazureAtomOperator along the sorting word of alpha to x^sort(alpha); t = 0 gives AtomPolynomial.";
TAtomPolynomial[alpha_?weakCompositionQ, x_, t_] := cached[{TAtomPolynomial, alpha},
	TDemazureAtomOperator[monomial[Sort[alpha, Greater], xx], xx, tt, sortingWord[alpha]]] /. {xx -> x, tt -> t};

permutationQ[w_] := VectorQ[w, IntegerQ] && Sort[w] === Range[Length[w]];

PermutationToCode::usage = "PermutationToCode[w] returns the Lehmer code of the permutation w (one-line notation): entry i counts j > i with w[[j]] < w[[i]].";
PermutationToCode[w_?permutationQ] := Table[Count[w[[i + 1 ;;]], v_ /; v < w[[i]]], {i, Length[w]}];

CodeToPermutation::usage = "CodeToPermutation[c] returns the permutation (one-line notation) with Lehmer code c, in the smallest symmetric group that contains it.";
CodeToPermutation[c_?weakCompositionQ] := Module[{n = Max[Length[c], Max[MapIndexed[#1 + First[#2] &, c], 0]], code, avail, w},
	code = PadRight[c, n]; avail = Range[n];
	w = Table[With[{v = avail[[code[[i]] + 1]]}, avail = DeleteCases[avail, v]; v], {i, n}];
	(* Drop trailing fixed points. *)
	While[Length[w] > 0 && Last[w] == Length[w], w = Most[w]];
	w
];

SchubertPolynomial::usage = "SchubertPolynomial[w, x] returns the Schubert polynomial of the permutation w (one-line notation), computed by divided differences from x[1]^(n-1) x[2]^(n-2) ... x[n-1] for the longest permutation of n letters.";
SchubertPolynomial[w_?permutationQ, x_] := cached[{SchubertPolynomial, w},
	Module[{n = Length[w]},
		(* Bubble-sorting w into decreasing order gives a word with
		   w s_i1 ... s_ik = w0, so S_w = d_i1 ... d_ik S_w0 (d_ik acting first). *)
		DividedDifference[Times @@ Table[xx[i]^(n - i), {i, n}], xx, sortingWord[w]]]] /. xx -> x;


(* ::Section:: *)
(* Basis symbols and conversions *)

CreateBasis[KeySymbol, "\[Kappa]", IndexType -> "WeakComposition",
	MultiplicationFunction -> None, PowerFunction -> None];
CreateBasis[AtomSymbol, "A", IndexType -> "WeakComposition",
	MultiplicationFunction -> None, PowerFunction -> None];
CreateBasis[SchubertSymbol, "\[GothicS]", IndexType -> "Permutation",
	MultiplicationFunction -> None, PowerFunction -> None];

KeySymbol::usage = "KeySymbol[alpha, x] represents the key polynomial kappa_alpha in the variables x[1], x[2], ... as a basis element; trailing zeros of alpha are removed. NonsymmetricToPolynomial expands it.";
AtomSymbol::usage = "AtomSymbol[alpha, x] represents the Demazure atom A_alpha in the variables x[1], x[2], ... as a basis element; trailing zeros of alpha are removed. NonsymmetricToPolynomial expands it.";
SchubertSymbol::usage = "SchubertSymbol[w, x] represents the Schubert polynomial of the permutation w in the variables x[1], x[2], ... as a basis element; trailing fixed points of w are removed. NonsymmetricToPolynomial expands it.";

NonsymmetricToPolynomial::usage = "NonsymmetricToPolynomial[expr, x] replaces KeySymbol, AtomSymbol and SchubertSymbol elements with alphabet x (or None) in expr by the corresponding polynomials in x[1], x[2], ..., and expands.";
NonsymmetricToPolynomial[expr_, x_] := Expand[expr /. {
	KeySymbol[a_List, x | None] :> KeyPolynomial[a, x],
	AtomSymbol[a_List, x | None] :> AtomPolynomial[a, x],
	SchubertSymbol[w_List, x | None] :> SchubertPolynomial[w, x]}];

(* Transition data in degree d and n variables: the monomial expansions of the basis
   indexed by all weak compositions (or codes) of d with n parts. The matrix is
   unitriangular for a suitable order, hence invertible over the integers. *)
transitionInverse[family_, d_Integer, n_Integer] := cached[{"transition", family, d, n},
	Module[{indices, rows},
		indices = Join @@ (Permutations /@ IntegerPartitions[d, {n}, Range[0, d]]);
		rows = Table[expansionVector[family, alpha, indices, n], {alpha, indices}];
		{indices, Inverse[rows]}]];

familyPolynomial["Key", alpha_, n_] := KeyPolynomial[alpha, xx];
familyPolynomial["Atom", alpha_, n_] := AtomPolynomial[alpha, xx];
familyPolynomial["Schubert", code_, n_] := SchubertPolynomial[CodeToPermutation[code], xx];

(* Coefficients of the monomials x^beta, beta in indices, of the polynomial p in x[1..n]. *)
coefficientVector[p_, x_, indices_, n_] := With[
	{rules = Association[CoefficientRules[p, x /@ Range[n]]]},
	Lookup[rules, Key /@ indices, 0]];

expansionVector[family_, alpha_, indices_, n_] :=
	coefficientVector[familyPolynomial[family, alpha, n], xx, indices, n];

familySymbol["Key", alpha_, x_] := KeySymbol[alpha, x];
familySymbol["Atom", alpha_, x_] := AtomSymbol[alpha, x];
familySymbol["Schubert", code_, x_] := SchubertSymbol[CodeToPermutation[code], x];

toFamilyBasis[family_, poly_, x_, nIn_] := Module[{p = Expand[poly], vars, n, s, total = 0},
	vars = Union@Cases[p, x[i_Integer] :> i, {0, Infinity}];
	n = Max[Append[vars, 1], nIn];
	(* Convert each homogeneous component separately. *)
	Do[With[{pd = Coefficient[Expand[p /. x[i_] :> s x[i]], s, d]},
		If[pd =!= 0,
			Module[{indices, inv, vec},
				{indices, inv} = transitionInverse[family, d, n];
				vec = coefficientVector[pd, x, indices, n];
				total += (vec . inv) . (familySymbol[family, #, x] & /@ indices)]]],
		{d, 0, Exponent[p /. x[i_] :> s x[i], s]}];
	total
];

ToKeyBasis::usage = "ToKeyBasis[poly, x] writes the polynomial poly in x[1], x[2], ... in the key basis, as a combination of KeySymbol[alpha, x].\nToKeyBasis[poly, x, n] uses keys in n variables (default: the largest variable index occurring).";
ToKeyBasis[poly_, x_, n_Integer: 0] := toFamilyBasis["Key", poly, x, n];

ToAtomBasis::usage = "ToAtomBasis[poly, x] writes the polynomial poly in x[1], x[2], ... in the basis of Demazure atoms, as a combination of AtomSymbol[alpha, x].\nToAtomBasis[poly, x, n] uses atoms in n variables (default: the largest variable index occurring).";
ToAtomBasis[poly_, x_, n_Integer: 0] := toFamilyBasis["Atom", poly, x, n];

ToSchubertBasis::usage = "ToSchubertBasis[poly, x] writes the polynomial poly in x[1], x[2], ... in the Schubert basis, as a combination of SchubertSymbol[w, x] (Schubert polynomials whose Lehmer code has length at most the number of variables).\nToSchubertBasis[poly, x, n] uses n variables (default: the largest variable index occurring).";
ToSchubertBasis[poly_, x_, n_Integer: 0] := toFamilyBasis["Schubert", poly, x, n];

End[];

Protect @@ Select[Names["NonsymmetricPolynomials`*"], !StringMatchQ[#, ___ ~~ "$" ~~ ___] &];

EndPackage[];
